micronaut:
  application:
    name: micronaut-kamal-postgresql
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ''
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.xml
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
